import uuid
from datetime import datetime
from pydantic import BaseModel, Field
from typing import List, Optional


class NegotiationSuggestionSchema(BaseModel):
    id: uuid.UUID
    clause_id: uuid.UUID
    suggestion_text: str
    created_at: datetime

    model_config = {"from_attributes": True}


class ClauseSchema(BaseModel):
    id: uuid.UUID
    clause_index: int
    raw_text: str
    summary: Optional[str] = None
    risk_type: Optional[str] = None
    risk_score: Optional[int] = None
    qdrant_point_id: Optional[uuid.UUID] = None
    created_at: datetime
    suggestions: List[NegotiationSuggestionSchema] = []

    model_config = {"from_attributes": True}


class ContractSummarySchema(BaseModel):
    id: uuid.UUID
    document_id: uuid.UUID
    title: Optional[str] = None
    counterparty_name: Optional[str] = None
    status: str
    created_at: datetime
    risk_clause_count: int = 0
    high_risk_count: int = 0

    model_config = {"from_attributes": True}


class ContractDetailSchema(BaseModel):
    id: uuid.UUID
    document_id: uuid.UUID
    title: Optional[str] = None
    counterparty_name: Optional[str] = None
    status: str
    created_at: datetime
    clauses: List[ClauseSchema] = []

    model_config = {"from_attributes": True}


# Schema for structured output generated by Gemini
class ClauseAnalysisAIResponse(BaseModel):
    summary: str = Field(description="One-sentence clear summary of the clause text.")
    risk_type: str = Field(description="Must be one of: 'penalty', 'lock_in', 'indemnity', 'termination', 'none'")
    risk_score: int = Field(description="Integer score from 0 to 100 representing risk severity (high score means high risk).")


class ContractMetadataAIResponse(BaseModel):
    title: str = Field(description="Official name or title of the agreement.")
    counterparty_name: str = Field(description="Identified counterparty or vendor name.")


class SuggestionAIResponse(BaseModel):
    suggestion_text: str = Field(description="Detailed plain-English recommendation for negotiating this clause, including draft alternative terms.")
